'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Resource1
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Shape_Editor.Resource1", GetType(Resource1).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property AboutDark() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("AboutDark", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property AboutLight() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("AboutLight", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property AddPointToolButtonDarkMode() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("AddPointToolButtonDarkMode", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property AddPointToolButtonLightMode() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("AddPointToolButtonLightMode", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property AddPointToolButtonSelectedDarkMode() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("AddPointToolButtonSelectedDarkMode", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property AddPointToolButtonSelectedLightMode() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("AddPointToolButtonSelectedLightMode", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property Airplane() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Airplane", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property Alien_Ship() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Alien Ship", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property CenterDrawingToolButtonDarkMode() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("CenterDrawingToolButtonDarkMode", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property CenterDrawingToolButtonLightMode() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("CenterDrawingToolButtonLightMode", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property ExitLight() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("ExitLight", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property MovePointToolButtonDarkMode() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("MovePointToolButtonDarkMode", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property MovePointToolButtonDarkModeSelected() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("MovePointToolButtonDarkModeSelected", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property MovePointToolButtonLightMode() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("MovePointToolButtonLightMode", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property MovePointToolButtonSelectedLightMode() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("MovePointToolButtonSelectedLightMode", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property NewFileLight() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("NewFileLight", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property OpenFileLight() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("OpenFileLight", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property SaveFileAsLight() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("SaveFileAsLight", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property SaveFileLight() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("SaveFileLight", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property SubtractPointToolDark() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("SubtractPointToolDark", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property SubtractPointToolLight() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("SubtractPointToolLight", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property SubtractPointToolSelectedDark() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("SubtractPointToolSelectedDark", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property SubtractPointToolSelectedLight() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("SubtractPointToolSelectedLight", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
    End Class
End Namespace
